import MainLayout from "@/components/main_layout"
import './globals.css'  

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    
    return (
        <html lang="en">
            <body>
                <MainLayout>
                    {children}
                </MainLayout>
            </body>
        </html>
    )
}