// src/app/layout.jsx
import MainLayout from "@/components/main_layout"
import { AuthProvider } from './lib/auth-context'; // اضافه کردن AuthProvider
import './globals.css'  

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    
    return (
        <html lang="en">
            <body>
                <AuthProvider> {/* اینجا AuthProvider اضافه شد */}
                    <MainLayout>
                        {children}
                    </MainLayout>
                </AuthProvider>
            </body>
        </html>
    )
}