"use client"

import { Breadcrumb, Layout, Menu, theme } from 'antd';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
const { Header, Content, Footer } = Layout;
const items = [
    { label: "Home", href: "./", key: "1" },
    { label: "Posts", href: "/posts", key: "2" },
    { label: "Categories", href: "/categories", key: "3" },
    { label: "About", href: "/about", key: "4" },
]


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function MainLayout({ children }) {
    const {
        token: { colorBgContainer, borderRadiusLG },
    } = theme.useToken();


    const pathname = usePathname()
    console.log(pathname)

    return (
        <html lang="en">
            <body>
                <Layout>
                    <Header style={{ display: 'flex', alignItems: 'center' }}>
                        <div className="demo-logo" />
                        <Menu
                            theme="dark"
                            mode="horizontal"
                            style={{ flex: 1, minWidth: 0 }}

                            selectedKeys={[pathname.split("/")[1]]}
                        >
                            {items.map((route) =>{
                                return(
                                    <Menu.Item key={route.key}>
                                        <Link key={route.key} href={route.href}>{route.label}</Link>
                                    </Menu.Item>
                                )
                            })}
                        </Menu>
                    </Header>
                    <Content style={{ padding: '0 48px' , background: '#e2ebf5ff' }}>
                        <Breadcrumb
                            style={{ margin: '16px 0' }}
                            items={[{ title: 'Home' }, { title: 'List' }, { title: 'App' }]}
                        />
                        <div
                            style={{
                                background: '#cad7e6ff',
                                minHeight: 280,
                                padding: 24,
                                borderRadius: borderRadiusLG,
                            }}
                        >
                            {children}
                        </div>
                    </Content>
                    <Footer style={{ textAlign: 'center' , background:'#e2ebf5ff' }}>
                        Ant Design ©{new Date().getFullYear()} Created by Ant UED
                    </Footer>
                </Layout>
            </body>
        </html>
    )
}